enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_INPUT = 'INVALID_INPUT',
  STALE_UPDATE = 'STALE_UPDATE',
  REQUEST_ERROR = 'REQUEST_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}

export = ErrorCodes;
